# agibot_x2_pkg/config/joint_limits.yaml
joint_limits:
  left_shoulder_pitch_joint:
    has_velocity_limits: true
    max_velocity: 3.14
    has_acceleration_limits: true
    max_acceleration: 5.0
  right_shoulder_pitch_joint:
    has_velocity_limits: true
    max_velocity: 3.14
    has_acceleration_limits: true
    max_acceleration: 5.0