# Parametri globali Octomap (alla radice del file)
octomap_frame: torso_link
octomap_resolution: 0.02  # 2 cm di risoluzione per distinguere i singoli libri
max_range: 2.0

# Elenco dei sensori 3D attivi
sensors:
  - head_camera

head_camera:
  sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
  image_topic: /head_camera/depth_image
  camera_info_topic: /head_camera/camera_info
  queue_size: 5
  near_clipping_plane_distance: 0.1
  far_clipping_plane_distance: 2.0
  shadow_threshold: 0.2
  padding_scale: 1.0
  padding_offset: 0.01
  max_update_rate: 2.0